export default function() {
    return [
        { number: 91, name: "Thomas Nielson", class: "Alpha Gamma", line: "151", big: "Andrew Ta", major: "Psychology", hometown: "Seattle, Washington", year: 4, ecab: false},
        { number: 93, name: "Allen Dao", class: "Alpha Delta", line: "112", big: "Ryan Nguyen", major: "Sociology", hometown: "Everett, Washington", year: 3, ecab: false},
        { number: 94, name: "Hang Thao", class: "Alpha Delta", line: "Wong Dynasty", big: "Kevin Wong", major: "Sociology", hometown: "Seattle, Washington", year: 5, ecab: false},
        { number: 96, name: "Brandon Lee", class: "Alpha Delta", line: "Wong Dynasty", big: "Quezan Wong", major: "", hometown: "", year: 3, ecab: false},
        { number: 97, name: "Shawn Yamane", class: "Alpha Delta", line: "Wong Dynasty", big: "Kevin Wong", major: "Psychology", hometown: "Kauai, Hawaii", year: 3, ecab: false},
        { number: 98, name: "Schawnery Lin", class: "Alpha Delta", line: "Crown Royal", big: "Raymond Yu", major: "Electrical Engineering", hometown: "Redmond, Washington", year: 3, ecab: false},
        { number: 99, name: "Alexander Wong", class: "Alpha Delta", line: "Legacy", big: "Jimmy Nguyen", major: "Informatics", hometown: "Huntington Beach, California", year: 3, ecab: true},
        { number: 101, name: "Aashray Anand", class: "Alpha Delta", line: "Scary Line", big: "Andrew Huynh", major: "Mathematics", hometown: "Seattle, Washington", year: 4, ecab: true},
        { number: 102, name: "Kevin Yu", class: "Alpha Delta", line: "Tradition of Excellence", big: "Sunny Kim", major: "Accounting", hometown: "Seattle, Washington", year: 4, ecab: true},
        { number: 103, name: "Peter Chen", class: "Alpha Delta", line: "Scary Line", big: "Andrew Huynh", major: "Business Marketing", hometown: "Pullman, Washington", year: 3, ecab: false},
        { number: 104, name: "Connor Chinn", class: "Alpha Delta", line: "Tradition of Excellence", big: "Phi-Ho Phan", major: "", hometown: "", year: "Alumni", ecab: false},
        { number: 105, name: "Ryan Yang", class: "Alpha Zeta", line: "Scary Line", big: "Aashray Anand", major: "Materials Science and Engineering", hometown: "Taipei, Taiwan", year: 2, ecab: false},
        { number: 106, name: "Brook Afework", class: "Alpha Zeta", line: "Big Liu, Inc.", big: "Sopheak Neak", major: "", hometown: "", year: 4, ecab: false},
        { number: 107, name: "Jonah Wu", class: "Alpha Zeta", line: "Tradition of Excellence", big: "Connor Chinn", major: "Applied and Computational Math Sciences", hometown: "Taipei, Taiwan", year: 2, ecab: false},
        { number: 108, name: "Anthony Nguyen", class: "Alpha Zeta", line: "Legacy", big: "Alexander Wong", major: "Human Centered Design and Engineering", hometown: "Redmond, Washington", year: 2, ecab: true},
        { number: 109, name: "Trey Michaels", class: "Alpha Zeta", line: "Tradition of Excellence", big: "Connor Chinn", major: "Informatics", hometown: "Bellevue, Washington", year: 2, ecab: false},
        { number: 110, name: "Lucas Mah", class: "Alpha Zeta", line: "Crown Royal", big: "Daniel Lee", major: "Human Centered Design and Engineering", hometown: "San Diego, California", year: 3, ecab: false},
        { number: 111, name: "Naveed Karimi", class: "Alpha Zeta", line: "Cheng Family", big: "Dominic Nguyen", major: "Communications", hometown: "Redmond, Washington", year: 4, ecab: false},
        { number: 112, name: "Jeehoon Park", class: "Alpha Zeta", line: "Tradition of Excellence", big: "Connor Chinn", major: "Biochemistry", hometown: "Cupertino, California", year: 3, ecab: false},
        { number: 113, name: "Francis Kwon", class: "Alpha Zeta", line: "Scary Line", big: "Peter Chen", major: "", hometown: "", year: 2, ecab: true},
        { number: 114, name: "Rome Lin", class: "Alpha Zeta", line: "Scary Line", big: "Peter Chen", major: "", hometown: "", year: 2, ecab: false},
        { number: 115, name: "David Wong", class: "Alpha Eta", line: "112", big: "Allen Dao", major: "Neurobiology", hometown: "San Ramon, California", year: 3, ecab: true},
        { number: 116, name: "Ethan Le", class: "Alpha Eta", line: "Tanamachi", big: "Oscar Luo", major: "Physiology", hometown: "Newcastle, Washington", year: 2, ecab: false},
        { number: 117, name: "Matt Cao", class: "Alpha Eta", line: "Wong Dynasty", big: "Hang Thao", major: "Sociology", hometown: "Newcastle, Washington", year: 4, ecab: false},
        { number: 118, name: "Joon Kim", class: "Alpha Eta", line: "Wong Dynasty", big: "Brandon Lee", major: "Business", hometown: "Mukilteo, Washington", year: 2, ecab: false},
        { number: 119, name: "Nathan Han", class: "Alpha Eta", line: "Kang", big: "Ben Chung", major: "Electrical Engineering", hometown: "Seattle, Washington", year: 2, ecab: false},
        { number: 120, name: "Ozan Erdal", class: "Alpha Eta", line: "Legacy", big: "Tony Xie", major: "Mathematics", hometown: "Irvine, California", year: 3, ecab: false}
    ];
}