export default function() {
    return [
        { name: 'A – University of California, Berkeley', inactive: false },
        { name: 'B – State University of New York, Stony Brook', inactive: true },
        { name: 'Γ – University of California, Davis', inactive: true },
        { name: 'Δ – San José State University', inactive: false },
        { name: 'Ε – University of California, Riverside', inactive: true },
        { name: 'Ζ – University of California, Santa Cruz', inactive: false },
        { name: 'Η – University of California, Irvine', inactive: false },
        { name: 'Θ – University of California, San Diego', inactive: false },
        { name: 'Ι – University of Michigan, Ann Arbor', inactive: false },
        { name: 'Κ – University of Arizona, Tucson', inactive: false },
        { name: 'Μ – Michigan State University, East Lansing', inactive: false },
        { name: 'Ν – University of North Carolina, Chapel Hill', inactive: false },
        { name: 'Ξ – University of Washington, Seattle', inactive: false },
        { name: 'O – University of California, Santa Barbara', inactive: false },
        { name: 'Π – University of Iowa', inactive: false },
        { name: 'Ρ – University of North Carolina, Charlotte', inactive: false },
        { name: 'Σ – Northwestern University', inactive: true },
        { name: 'Τ – North Carolina State University', inactive: false },
        { name: 'Υ – San Francisco State University', inactive: false },
        { name: 'Φ – Drexel State University', inactive: false },
        { name: 'Associate Chapter – State University of New York – Buffalo', inactive: true },
        { name: 'Colony – University of Nevada, Las Vegas', inactive: false },
        { name: 'Colony – University of Delaware', inactive: false },
        { name: 'Colony – Iowa State University', inactive: false },
        { name: 'Colony – Arizona State University', inactive: false },
        { name: 'Colony – Clemson University, inactive: false' }
    ];
}