export default function() {
    return [
        { title: 'National History of Pi Alpha Phi'},
        { text: 'Our long-established tradition of brotherhood was established in 1929 at the University of California, Berkeley. The fraternity of Pi Alpha Phi was founded by six unique individuals: Mr. D. Wing Tom, Mr. Wing Chan, Mr. Elmer Leong, Mr. Chack Chan, Mr. Tim Jang, and Mr. George Lee. Mr. Wing Chan was elected as the first President of the fraternity. Mr. D. Wing Tom served as the Vice President and Mr. Elmer Leong as the Secretary. They wanted to establish an organization that would be based on the bonds of friendship, mutual experience, academic excellence, and brotherhood. The name Pi Alpha Phi was derived from the initials of the Greek phrase meaning' },
        { quote: '"To advance through brotherly ties; the thirst for learning."' },
        { text: 'During this era, traditional Greek fraternities legally discriminated against all men of color. Since they were banned from joining a traditional Greek fraternity, the Founding Fathers wanted to ensure that Asian Awareness would always be an important part of the fraternity.Pi Alpha Phi is the first Asian American interest fraternity. Since the founding of Pi Alpha Phi, our Fraternity has flourished with active chapters at campuses throughout the nation.Today, the basic premise of the Fraternity remains largely unchanged. With brotherhood as our immutable asset, the lifelong bonds that we develop extend far beyond the university setting. Although the Fraternity is open to individuals of all ethnic backgrounds, it still retains its Asian American character. The basic goals of brotherhood achieved through shared experience, friendship and academic excellence remain unaltered. Although the organization evolves from generation to generation, the underlying vision and heart of the Fraternity is as solid today as it was for six young Berkeley men in 1926.'},
        { title: 'History of Pi Alpha Phi at UW' },
        { text: 'The origin of Pi Alpha Phi at the University of Washington first began with a common objective, to establish an organization that would serve as a means of making a profound impact on the University of Washington campus as well as an organization built upon the notion of developing and sustaining leaders amongst its peers – particularly those of Asian-American descent.In search of a means of accomplishing this feat, the eventual Founding Fathers discovered the fraternity of Pi Alpha Phi, the nation’s first Asian-American interest fraternity and an organization founded in 1926 on the principles of Academic Excellence, Asian Awareness, Brotherhood, Leadership, and Philanthropy.Beginning in the Spring of 2003, this group of individuals sought out to bring the “Tradition of Excellence” to the University of Washington. With a strong determination to make a difference, they made a number of visits to existing chapters across the nation, learning the traditions and history of the Fraternity, what it stands for and how it became what it is today.On March 22, 2004, twelve young men, Mr. Terry Tan, Mr. Jonathan Tam, Mr. Phong Nguyen, Mr. Bruce Chhay, Mr. Eugene Choi, Mr. Joshua Ng, Mr. Stanley Choo, Mr. Gary Fong, Mr. Johnny Wong, Mr. Daniel Cheng, Mr. Vinh Nguyen, and Mr. Tony Liu, rose to become Founding Fathers of a new legacy at the University of Washington – the unbreakable brotherhood of Pi Alpha Phi.' }
    ];
}