export default function() {
    return [
        { number: 1, name: "Terry Tan", class: "Charter", active: false },
        { number: 2, name: "Jonathan Tam", class: "Charter", active: false },
        { number: 3, name: "Phong Nguyen", class: "Charter", active: false },
        { number: 4, name: "Bruce Chhay", class: "Charter", active: false },
        { number: 5, name: "Eugene Choi", class: "Charter", active: false },
        { number: 6, name: "Joshua Ng", class: "Charter", active: false },
        { number: 7, name: "Stanley Choo", class: "Charter", active: false },
        { number: 8, name: "Gary Fong", class: "Charter", active: false },
        { number: 9, name: "Johnny Wong", class: "Charter", active: false },
        { number: 10, name: "Daniel Cheng", class: "Charter", active: false },
        { number: 11, name: "Vinh Nguyen", class: "Charter", active: false },
        { number: 12, name: "Tony Liu", class: "Charter", active: false },
        { number: 14, name: "Daniel Kim", class: "Alpha", active: false },
        { number: 15, name: "Andy Huang", class: "Alpha", active: false },
        { number: 17, name: "Raymond Choi", class: "Alpha", active: false },
        { number: 18, name: "Marco Gutierrez", class: "Beta", active: false },
        { number: 19, name: "Dan Le", class: "Beta", active: false },
        { number: 20, name: "Heing Lim", class: "Beta", active: false },
        { number: 21, name: "James Lo", class: "Beta", active: false },
        { number: 22, name: "Richard Chuong", class: "Delta" , active: false },
        { number: 23, name: "Bobby Southavong", class: "Delta", active: false },
        { number: 24, name: "Cuong Q. Nguyen", class: "Delta", active: false },
        { number: 25, name: "Carlos Gutierrez", class: "Delta", active: false },
        { number: 26, name: "James Hu", class: "Zeta", active: false },
        { number: 27, name: "Willy Cheung", class: "Zeta", active: false },
        { number: 28, name: "Dudley Monfort", class: "Zeta", active: false },
        { number: 29, name: "Justin Chan", class: "Eta", active: false },
        { number: 30, name: "Jinu Park", class: "Eta", active: false },
        { number: 31, name: "Terence Tep", class: "Eta", active: false },
        { number: 32, name: "Stephen Gillie", class: "Eta", active: false },
        { number: 33, name: "Blaine Matsuura", class: "Eta", active: false },
        { number: 34, name: "Wei Dai", class: "Eta", active: false },
        { number: 35, name: "Eric Choi", class: "Eta", active: false },
        { number: 36, name: "David Fukuyama", class: "Iota", active: false },
        { number: 37, name: "Vincent Nguyen", class: "Iota", active: false },
        { number: 38, name: "Hai Le", class: "Iota", active: false },
        { number: 40, name: "Amado Robancho", class: "Kappa", active: false },
        { number: 41, name: "Jesse WalkingChild", class: "Kappa", active: false },
        { number: 42, name: "Tyrone Hall-Deal", class: "Kappa", active: false },
        { number: 43, name: "Steven U", class: "Mu", active: false },
        { number: 44, name: "Adam Baughman", class: "Mu", active: false },
        { number: 45, name: "Ted Whang", class: "Mu", active: false },
        { number: 46, name: "Young Jeong", class: "Mu", active: false },
        { number: 48, name: "Viktor Mu", class: "Nu", active: false },
        { number: 49, name: "Eric Hutchinson", class: "Nu", active: false },
        { number: 50, name: "Tommy Thai", class: "Xi", active: false },
        { number: 51, name: "Levin Le", class: "Xi", active: false },
        { number: 52, name: "Jonathon Nguyen", class: "Xi", active: false },
        { number: 53, name: "Danny Hoy", class: "Xi", active: false },
        { number: 54, name: "Jeffrey Le", class: "Xi", active: false },
        { number: 55, name: "Eugene Mu", class: "Xi", active: false },
        { number: 56, name: "Oak Nguyen", class: "Omicron", active: false },
        { number: 57, name: "Douglas Chung", class: "Omicron", active: false },
        { number: 58, name: "Howard Lin", class: "Rho", active: false },
        { number: 59, name: "Phi-Ho Phan", class: "Rho", active: false },
        { number: 60, name: "Minh Nguyen", class: "Rho", active: false },
        { number: 61, name: "Maric Sobreo", class: "Sigma", active: false },
        { number: 62, name: "Brian Chia", class: "Sigma", active: false },
        { number: 63, name: "Jimmy Nguyen", class: "Tau", active: false },
        { number: 64, name: "Alex Searle", class: "Tau", active: false },
        { number: 65, name: "Brandon Hadi", class: "Tau", active: false },
        { number: 66, name: "Robert Choi", class: "Tau", active: false },
        { number: 67, name: "Jeff Kwok", class: "Tau", active: false },
        { number: 68, name: "Jesse Wu", class: "Tau", active: false },
        { number: 69, name: "Hyojin Kim", class: "Tau", active: false },
        { number: 70, name: "Paul Nguyen", class: "Tau", active: false },
        { number: 71, name: "Jason Kim", class: "Upsilon", active: false },
        { number: 72, name: "Kevin Penaloza", class: "Upsilon", active: false },
        { number: 73, name: "Sunny Kim", class: "Upsilon", active: false },
        { number: 74, name: "Victor Nguyen", class: "Upsilon", active: false },
        { number: 75, name: "Michael Kim", class: "Phi", active: false },
        { number: 76, name: "Sirfame Lin", class: "Phi", active: false },
        { number: 77, name: "Jimmy Merino-Cruz", class: "Phi", active: false },
        { number: 78, name: "Andrew Ta", class: "Psi", active: false },
        { number: 79, name: "Jordan Epistola", class: "Psi", active: false },
        { number: 80, name: "Sopheak Neak", class: "Psi", active: false },
        { number: 81, name: "Lawrence Tep", class: "Psi", active: false },
        { number: 82, name: "Ryan Nguyen", class: "Psi", active: false },
        { number: 83, name: "Tony Xie", class: "Psi", active: false },
        { number: 84, name: "Daniel Lee", class: "Psi", active: false },
        { number: 85, name: "Kevin Su", class: "Psi", active: false },
        { number: 86, name: "Quezan Wong", class: "Alpha Alpha", active: false },
        { number: 87, name: "Kevin Wong", class: "Alpha Alpha", active: false },
        { number: 88, name: "Andre Huang", class: "Alpha Alpha", active: false },
        { number: 89, name: "Raymond Yu", class: "Alpha Beta", active: false },
        { number: 90, name: "Andrew Huynh", class: "Alpha Beta", active: false },
        { number: 91, name: "Thomas Nielson", class: "Alpha Gamma", active: true },
        { number: 92, name: "Mason Ma", class: "Alpha Gamma", active: false },
        { number: 93, name: "Allen Dao", class: "Alpha Delta", active: true },
        { number: 94, name: "Hang Thao", class: "Alpha Delta", active: true },
        { number: 95, name: "Dominic Nguyen", class: "Alpha Delta", active: false },
        { number: 96, name: "Brandon Lee", class: "Alpha Delta", active: true },
        { number: 97, name: "Shawn Yamane", class: "Alpha Delta", active: true },
        { number: 98, name: "Schawnery Lin", class: "Alpha Delta", active: true },
        { number: 99, name: "Alexander Wong", class: "Alpha Delta", active: true },
        { number: 100, name: "Henry Tran", class: "Alpha Delta", active: true },
        { number: 101, name: "Aashray Anand", class: "Alpha Delta", active: true },
        { number: 102, name: "Kevin Yu", class: "Alpha Delta", active: true },
        { number: 103, name: "Peter Chen", class: "Alpha Delta", active: true },
        { number: 104, name: "Connor Chinn", class: "Alpha Delta", active: true },
        { number: 105, name: "Ryan Yang", class: "Alpha Zeta", active: true },
        { number: 106, name: "Brook Afework", class: "Alpha Zeta", active: true },
        { number: 107, name: "Jonah Wu", class: "Alpha Zeta", active: true },
        { number: 108, name: "Anthony Nguyen", class: "Alpha Zeta", active: true },
        { number: 109, name: "Trey Michaels", class: "Alpha Zeta", active: true },
        { number: 110, name: "Lucas Mah", class: "Alpha Zeta", active: true },
        { number: 111, name: "Naveed Karimi", class: "Alpha Zeta", active: true },
        { number: 112, name: "Jeehoon Park", class: "Alpha Zeta", active: true },
        { number: 113, name: "Francis Kwon", class: "Alpha Zeta", active: true },
        { number: 114, name: "Rome Lin", class: "Alpha Zeta", active: true },
        { number: 115, name: "David Wong", class: "Alpha Eta", active: true },
        { number: 116, name: "Ethan Le", class: "Alpha Eta", active: true },
        { number: 117, name: "Matthew Cao", class: "Alpha Eta", active: true },
        { number: 118, name: "Joon Kim", class: "Alpha Eta", active: true },
        { number: 119, name: "Nathan Han", class: "Alpha Eta", active: true },
        { number: 120, name: "Ozan Erdal", class: "Alpha Eta", active: true }
    ];
}