export default function() {
    return [
        { text: 'Brotherhood, Philanthropy and Leadership. The pursuit of Academic Excellence, Asian Awareness and Honor. More than 80 years after the establishment of our founding chapter at the University of California, Berkeley, the Mission Statements of Pi Alpha Phi remain an integral part of our daily lives. Membership in the Fraternity teaches us not only the benefits of being a Fraternity man, but also how to be a better man.' },
        { text: 'Pi Alpha Phi is an extraordinary Fraternity with a storied past and promising future. Our Fraternity has been in existence longer than any other Asian-American Interest Fraternity. Pi Alpha Phi is older than such commercial icons as Starbuck’s, Federal Express, and American Airlines.' },
        { text: 'Since 1929, our members have become pioneers in business, law, medicine, politics, higher education, science, and nearly every other field imaginable. Our brothers – both undergraduate and alumni – seek to serve as model citizens in a contemporary world that is not always receptive of Fraternity membership. They seek to break down the stereotypes of brotherhood and construct relationships built on honesty, respect and compassion.' },
        { text: 'With good reason, prospective members always ask, “What makes Pi Alpha Phi special? What makes your Fraternity different?”' },
        { text: 'Are we the largest national fraternity? No. Do we have the most active members? No.' },
        { text: 'The answer is simple: Without a doubt, our rich history and traditions, strong brotherhood and our alumni members make us the dynamic, progressive organization that we are today. For generations, our alumni members have served as role models to future leaders of both our country and abroad. Whether they have shaped the laws and policies of the United States, performed scientific experiments in top medical institutions around the world, or guided the world’s largest and most successful companies, our members and brotherhood truly do make a difference in the world.' },
        { text: 'Membership in Pi Alpha Phi does not guarantee success in life, but as a member of the Fraternity, the opportunity for success is available to you if you seek it out. Clearly, we cannot say that every member of Pi Alpha Phi will gain instant status and affluence. The opportunity, however, is there and waiting for you to grasp it. Membership in Pi Alpha Phi offers leadership skills, brotherhood, personal and professional development, responsibility, alumni networking and life-long friendships. Pi Alpha Phi’s strong “brotherhood” – while an intangible concept – is a definite reality and is alive and well within the confines of our Fraternity.' },
        { text: 'For more information about how to join Pi Alpha Phi email uwpaphi@uw.edu.' }
    ];
}